//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftPoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenusConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenusConfiguration()
        {
            this.MenusRights = new HashSet<MenusRight>();
        }
    
        public int ConfigurationId { get; set; }
        public Nullable<int> MenuId { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string ActionDescription { get; set; }
    
        public virtual Menu Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenusRight> MenusRights { get; set; }
    }
}
