//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftPoint.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenusRight
    {
        public int RightsId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> ConfigurationId { get; set; }
        public Nullable<System.DateTime> RowCreated { get; set; }
        public Nullable<long> RowCreatedByUserId { get; set; }
    
        public virtual MenusConfiguration MenusConfiguration { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
